### ISSUE TITLE
Weapon Box annoying bug

### ISSUE THREAD

**Issue by Enter03** [Fexcraft/FlansMod#21]
Hello!
If I have for an example 64 ingots of iron and if I will open Weapon Box, then my ingot ItemStack count will be zero. 

Because my English is very very baad :( i recorded a video of this bug, here is link: https://www.youtube.com/watch?v=UGYZwofOYHw&feature=youtu.be
(Maybe video quality isn't the best, but it is only to show error)

If you will fast click "Craft" button, then item will be crafter... but it is very annoying - Please fix it :)

**Comment by Fexcraft** [comment]
prubowałeś bez niczego obok (block)?
(ja tam nie dotykałem nic takiego przy kodzie od GUI, także niewiem co to może powodować. :o)

_No, I'm not polish, but I can it fluently._

**Comment by Enter03** [comment]
Dzięki za szybką odpowiedź, wygląda na to, że to błąd z oryginalnego Flan's Moda... ten błąd występuje też w Vehicle Crafting Table, nic nie jest do niego podłączone, żadne rury z innych modów - to błąd wewnątrz kodu Twojego projektu.

--- (Google Translate)
Thanks for the quick reply, it appears that an error of original Flan's mod... This error occurs also in Vehicle Crafting Table, nothing is connected to it, no pipes (or item stealers :P) from other mods - i think it's bug in your code.

**Comment by Enter03** [comment]
Effect without anthing connected to Weapon Box: https://www.youtube.com/watch?v=OecDXHRr1Ws
---
Efekt nie podłączenia niczego do Weapon Box'a: https://www.youtube.com/watch?v=OecDXHRr1Ws

PS. Czy mógłbyś proszę naprawić ten błąd z pojazdami? (Issue #8 - https://github.com/Fexcraft/FlansMod/issues/8) to jest nie do zniesienia, zwłaszcza w samolotach, pomógł bym ale ja znam C# (.Net) a nie Javę :'(

**Comment by Fexcraft** [comment]
Pare razy w różne sposoby probawałem.. nici z tego :[
Może sprubuje "re-write", choć to sprawa dająca dość duże bule głowy z powodu ilości kodu.. conajmniej narazie..

C# dość podoble do Java, conajmniej z tego co widziałem w Unity 0.o

**Comment by Enter03** [comment]
Dziękuję za próby naprawienia (rewrite rzeczywiście jest dobrym pomysłem, ale ja na Pana miejscu zają bym się przedewszystkim błędem #8, bo jest on dużo bardziej nieznośny), trzymam kciuki, za Pana pracę! Sam też może zainstaluję Eclipse i spróbuję coś zrobić, ale wątpię czy mi się uda.

PS. Tak, Java i C# są do siebie podobne, ale **tylko i wyłącznie składnią**, biblioteki są trochę inne, i ogólnie IDE do C# (Visual Studio) jest dużo bardziej przyjazne niż Eclipse.
Pozdrawiam :)!

**Comment by Fexcraft** [comment]
Ależ ja mówiłem tym razem o rewrite pojazdów :0

**Comment by Enter03** [comment]
Czy są już jakieś informacje w sprawie tego błędu? Czy domyśla się może Pan co może powodować ten problem? Nie wiem czy już to napisałem ale taki sam błąd występuje również w stole do tworzenia różnych pojazdów. (Ogólnie w różnych stołach w Flan's Modzie, błąd ten nie dotyczy chyba tylko stołu do modyfikacji pistoletów) Proszę o naprawienie tego.

Z góry dzięki i pozdrawiam!

**Comment by Fexcraft** [comment]
ogólnie wszystkie GUI są rozwalone...
