### ISSUE TITLE
About the 1.11+ version.

### ISSUE THREAD

**Issue by Fexcraft** [Fexcraft/FlansMod#22]
In 1.11 all block/items have to be lowercase, this caused part of the mod to have "Missing Textures",
only way to fix it is to rename all texture files to lowercase, same also goes for inner of the lang/json files which should have lowercase names/path/adresses.
_**This obviously applies to content packs too.**_

All vehicle/item/etc. names are automatically set by the game to lowercase, just remember that older game worlds will be incompatible and will delete the items as soon as you try to load them with the 1.11 version.
I do not know if there is a "Converter" to edit the data in the world saves, but isn't in my priority list aswel.

**Comment by mgdgfbhevdyeh** [comment]
Many MOD also had a similar problem.

**Comment by Fexcraft** [comment]
Currently trying to fix the "kick-out" issue and similar things while working on 1.11 mods,
but since the 1.11 code is very similar to 1.10.2, I should be able to port it to that version after I find a fix.

Other then that, the mod **kind of** is playable. So just compiling it and it's _'good'_ to go.

**Comment by Fexcraft** [comment]
I'm also not sure yet where to release the file. (upload)
I guess I'll use my own website.

**Comment by hunter688** [comment]
Json content(assets) can be lowercased using:
<pre>
find . -name "*.json" -exec sed -i "s/\(.*\)/\L\1/" '{}' \;
</pre>
Filenames inside assets dir can be lowercased by:
<pre>
exit 0
for SRC in `find assets -depth`
do
    DST=`dirname "${SRC}"`/`basename "${SRC}" | tr '[A-Z]' '[a-z]'`
    if [ "${SRC}" != "${DST}" ]
    then
        [ ! -e "${DST}" ] && mv -T "${SRC}" "${DST}" || echo "${SRC} was not renamed"
    fi
done
</pre>
Content of lang files (items,blocks) will be better modify by hand

**Comment by hunter688** [comment]
Guns cannot shoot, looks like not accept reloading magazine. When press right mouse button reload again and again instead of firing.

**Comment by Fexcraft** [comment]
All except Vehicle packets are disabled cause I wanted to know what was breaking the network stuff.
Also I don't plan to update guns, Neither was I the person who did it in 1.10.2;

**Comment by Enter03** [comment]
Hi Fex! I downloaded 1.10 release (this one: (1.10) FlansMod Minus 5.F0.2 - Experimental) but I think that this file isn't release version... it's not pre-alpha. I can't even use vehicles, it disconnect's from server (something in packets code is broken [I thing]). I know that this is "_Compiled due to existing request for a compiled file, I do not guarantee that the vehicles work as well as in the 1.11 version._" but please make 1.10 version as awesome as 1.11 :)

I run a server with my 3 friends, and I can't imagine it without Flan's Mod. And I also (like many people that are using this mod) can't update to 1.11 because of other mods.

And thanks for all updates that you made. Have a nice day!

**Comment by Enter03** [comment]
Hey! I want to translate your mod to Polish... maybe my English isn't the best but I can read it and convert to my home language.

Also I know Json, XML and I can translate e.g. Log messages and other things (GUI etc). I can translate some Flans Mod packs too :)

**Comment by Fexcraft** [comment]
hmm, well, most things which are translate-able are in the lang file.

**Comment by Enter03** [comment]
I had some time and translated your en_US.lang file - here is Polish version: (I don't have push access to this repository so I'm sending file this way)

[pl_PL.lang.txt](https://github.com/Fexcraft/FlansMod/files/1524248/pl_PL.lang.txt)

**Comment by Fexcraft** [comment]
Hmm, isn't usually the procedure to `fork` a repository, edit and then make a pull request?

**Comment by Enter03** [comment]
Ok, I made pull request. Hehe I'm really new to Github (and Git system) - I never used it before.
