### ISSUE TITLE
Ideas, Enchancements and Fixes.

### ISSUE THREAD

**Issue by Fexcraft** [Fexcraft/FlansMod#23]
- - - -
**Vehicles**
- ~~paintable vehicle parts~~ `done`
- ~~custom texture from URL~~ `done`
- cargo rendering `in progress`
- ~~lock feature~~ `done`
- - - -
**Items**
- properly working paint can (maybe gui?) `queued`
- x
- - - -
**Other**
- x
- x
- - - -
You can suggest new features also.
_this all applies for **FlansMod Minus** forks, not the default update fork_
see #2

**Comment by AGiLE-EaGLE1994** [comment]
I have a feature suggestion: Remaking vehicle weapons?
I really wish my planes could use their missiles and bombs.
I don't care at all about the handheld guns.
