### ISSUE TITLE
Building?

### ISSUE THREAD

**Issue by uwillparish** [Fexcraft/FlansMod#27]
I'm new to this, so how would i go about building the source into a jar with gradle?

**Comment by Tsoccerguy3** [comment]
Read how to install at sites . download and install Git for windows and Gradle from here
https://git-scm.com/download/win
https://gradle.org/install
Open the Git command window
copy repo to clipboard
git clone 'the repo name'
git checkout 'branch'
gradle build

**Comment by Fexcraft** [comment]
Damn this, accidentally closed the tab in which I had a full reply for this.

Basically, I myself use a "fused" workspace where I have the code of all my mods and flansmod
and only copy/push changes later to github/folder, thus I personally don't use the gradle stuff of this repo.
a.k.a. I keep forgetting to update/explain it.

**Comment by Pierresa15** [comment]
Thanks you Fex to have made a Flan's mod 1.10.2 ! It's very cool, but i have a problem when i launch the gradlew build...
`This mapping 'snapshot_20160518' was designed for MC 1.9.4! Use at your own peril.This mapping 'snapshot_20160518' was designed for MC 1.9.4! Use at your own peril.

#################################################
         ForgeGradle 2.2-SNAPSHOT-7f5a769        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP unknown               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
:deobfCompileDummyTask
:getVersionJson
:extractUserdev
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches SKIPPED
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:deobfMcMCP SKIPPED
:sourceApiJava
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20.653 secs
`

**Comment by Fexcraft** [comment]
Hmm, if you need a working jar,
https://github.com/Fexcraft/FlansMod/releases

**Comment by Pierresa15** [comment]
Thanks you very much Fexcraft ! The mods work !
But I can't see textures of the differents items x) Sorry ^^
