### ISSUE TITLE
FCL Mirror?

### ISSUE THREAD

**Issue by gitgud-software** [Fexcraft/FlansMod#3]
The present way of accessing the FCL dependency entails logging into your website and being subjected to adfocus, then manually adding the mod as an external jar. This is a bit of a pain over simple pulling in the dependency during the gradle setup, would it be ok to host an FCL mirror for that purpose?

On a separate note, your current site could really use clean CSS. And using noisy images as backgrounds really does a number on readability, along with the serif fonts.

I suggest using http://werc.cat-v.org/ or something similar in design.

I can offer a mirror from https://telecommand.space/ if that's agreeable.

EDIT: I found FCL here, it may be a good idea to specify you can acquire FCL without visiting your site.

https://minecraft.curseforge.com/projects/fexcraft-common-library

**Comment by Fexcraft** [comment]
I suggest looking there :P
https://github.com/Fexcraft/FlansMod/tree/1.10.2/libs

**Comment by gitgud-software** [comment]
Yeah, I'm not going to be too hard on it. Fexcraft looks like a really neat concept with a lot of work behind it, but the site in its current state might put people off.
