### ISSUE TITLE
Struggling to find your 1.10.2 port?

### ISSUE THREAD

**Issue by Pulverizer** [Fexcraft/FlansMod#32]
Hi, I'm looking for the 1.10.2 port with working guns? Also, did you manage to get the vehicles working?

**Comment by Fexcraft** [comment]
Who knows.
1.10.2 is pretty old by now, if there is anything, it's at https://github.com/Fexcraft/FlansMod/releases.

**Comment by Pulverizer** [comment]
@Fexcraft I tried there but there are only version numbers that far back.

**Comment by Fexcraft** [comment]
Chance there is it was never compiled/uploaded here.

Guns still existed in https://github.com/Fexcraft/FlansMod/tree/1.10.2
`Stable` vehicles are in https://github.com/Fexcraft/FlansMod/tree/minus-1.10.2 and newer.

**Comment by Pulverizer** [comment]
@Fexcraft could I convince you to make a completely working version?

**Comment by Fexcraft** [comment]
For 1.10 and with guns? I doubt it.

**Comment by Pulverizer** [comment]
I would be willing to pay a little if it helps

**Comment by Fexcraft** [comment]
I `will not` update guns or weapons.

Vehicles could back-port from the newer `minus` branches.

**Comment by Pulverizer** [comment]
Okay, I'm guessing you're one of those people they doesn't like guns? I'm fine with that if that's how you feel about it.

As far as I aware your last update to the 1.10 version had guns working but not vehicles so if you could backport your vehicle code I'd be happy.

**Comment by Fexcraft** [comment]
Small misunderstanding, I will not touch the 1.10 branch also,
with the backport I meant e.g. `minus-1.12` -> `minus-1.10.2`.
