### ISSUE TITLE
Leopard 2A6 Renders Improperly

### ISSUE THREAD

**Issue by gitgud-software** [Fexcraft/FlansMod#4]
Seems all of the textures that are supposed to form the top surface of the tank don't render properly. This tank is from the Flan's WWII pack.

![2016-09-16_15 35 55](https://cloud.githubusercontent.com/assets/10673048/18599047/53ba0d66-7c24-11e6-8640-6f275d9d4f06.png)

**Comment by Fexcraft** [comment]
It's anything except the rear for me.
![2016-09-17_21 07 32](https://cloud.githubusercontent.com/assets/11726534/18610376/70412076-7d1b-11e6-92f5-9c58e5e0368b.png)

**Comment by Fexcraft** [comment]
Hmm.. or it's rather random...
http://prntscr.com/cjwy71
http://prntscr.com/cjwyh7

**Comment by Fexcraft** [comment]
Fixed in #13
http://prntscr.com/cpn81x
