### ISSUE TITLE
Item Names Improperly Formatted

### ISSUE THREAD

**Issue by gitgud-software** [Fexcraft/FlansMod#5]
The display names for items could use some cleaning up. This problem affects all items across all packs at the moment.
![2016-09-16_15 36 29](https://cloud.githubusercontent.com/assets/10673048/18599172/f6b4ac60-7c24-11e6-842a-766590343762.png)

**Comment by Fexcraft** [comment]
It's cause of how flansmod registered (quite much against norms) in earlier versions,
the FCL library registers it to match the new Forge Registry for Items/Blocks.
(I could tinker around to register the unlocalised names like they were before, but that was actually not how I was told it should be).

**Comment by gitgud-software** [comment]
I think the way you're registering is right, just missing localization then. If I recall that's supposed to be done with a new class.

**Comment by Fexcraft** [comment]
Editing lang files should be enough, had to do something similar when updating my mods from 1.9 -> 1.10.x

(in my case it was renaming "modid_itemid" to "modid:itemid")

**Comment by Fexcraft** [comment]
Latest commit(s) should have fixed it.
![2016-09-17_21 05 58](https://cloud.githubusercontent.com/assets/11726534/18610354/ef721bf8-7d1a-11e6-9755-3da3cb0e5f52.png)
