### ISSUE TITLE
Guns Do Not Render

### ISSUE THREAD

**Issue by gitgud-software** [Fexcraft/FlansMod#6]
Already declared a non-priority issue but nonetheless it's still a problem with the current setup. Guns do not render properly nor do their sounds work at all. Despite not displaying, they still seem to work as intended and can be reloaded, fired, and upgraded otherwise.

**Comment by Fexcraft** [comment]
About sound: https://github.com/Fexcraft/FlansMod/issues/7

**Comment by Fexcraft** [comment]
An idea that came now is... maybe trying to hook up an forge event for rendering and force the model render then.

I remember that long ago when I tried(experimented) how to get an entity to render properly, one try ended up that the entity was rendered "inside" the steve model.

**Comment by Fexcraft** [comment]
https://github.com/Fexcraft/FlansMod/pull/9 seems to have fixed it, at least partially.
(didn't really check code any much, but it renders 0.o)
