### ISSUE TITLE
Vehicle Sounds Missing

### ISSUE THREAD

**Issue by gitgud-software** [Fexcraft/FlansMod#7]
The engine and turning sounds for all vehicles are broken.

**Comment by Fexcraft** [comment]
They aren't. It's simply 'disabled' (commented out).

I didn't remember the sound playing code so I just commented it out and marked with //TODO to find it easier.
If I recall right I might have code for playing sound in FSU, how to register sounds gotta check.

**Comment by Fexcraft** [comment]
Check if this fixed it. https://github.com/Fexcraft/FlansMod/commit/3d3c69b326a0c6d2dc74d1e74b1150e531a4153a
