### ISSUE TITLE
Visual "kick" of the player from a vehicle.

### ISSUE THREAD

**Issue by Fexcraft** [Fexcraft/FlansMod#8]
_**Source of Issue**_: unknown.

It existed also in my earlier try to update flansmod, thought the rewrite might help, but it perhaps it didn't.

**How it happens**:
When driving whichever vehicle, it seems to "kickout" the player off the vehicle,
and the vehicle just keeps moving, but when pressing "LSHIFT"/dismount key
the player is ("teleported") right near the vehicle, and the vehicle beheaves like it should when someone dismounts.

Possible cause could be the new weird "anti-cheat" (or whatever it is) of Minecraft.
(e.g. kicking "back" a player when flying fast in GM1)
<s>The bug happens even on lower speeds though.</s>

**Edit:** Other causes which I think could be it:
- packet sending/receive error
- bugs in vehicle code

**Comment by PrototypeTheta** [comment]
This is an old bug that has plagued the mod since the dark ages.

I am pretty convinced that it is an issue with packets, I've been plumbing the vehicle code for months now and I can't find anything that could cause this.

It may even be related to another bug I have experienced in my 1.7.10 build, where the player and vehicle would spontaneously be teleported to Nan/Nan/Nan at random while the vehicle was lodged in terrain. I have overcome this by resetting the throttle whenever the vehicle "crashes" and thus far I have not been able to reproduce the bug. But keep an eye out for it here.

**Comment by Fexcraft** [comment]
Ye, in the last days when I thought about it, it's pretty much like an bug I experienced on a 1.7.10 modded server (rather large modpack).
Never experienced this on Minecraft with a few mods only though,
so that's why I didn't think about that at first.

**Comment by PrototypeTheta** [comment]
For some reason it wasn't a problem in the 1.6.4 builds. When I last spoke to Flan about it (well over a year ago) he said it was present in 1.7.10 because they changed chunk loading. I noticed it tended to happen whenever there were considerable lag spikes and a large number of ticks were skipped. I have noticed even other vehicle mods like MCheli appear to be afflicted with a problem similar to this, only the player remains in the vehicle and continues flying after remaining stationary for a short period of time.

I'm no expert on packets (pretty damn abysmal with them if I must say so) but from what I know the packet handling stuff in the mod is pretty ancient, and I do remember hearing someone talk about the older systems having problems. It could potentially stem from that, but I can't say with any certainty.

**Comment by PrototypeTheta** [comment]
And just to clarify, is this only a problem with planes or is it happening with ground vehicles as well?

If the latter, I would call this a pretty good reason to panic.

**Comment by Fexcraft** [comment]
Vehicles in less then a minute~
Planes like in a few seconds. (the ones I tried)
(probably because of the acceletation difference)

About Packets... well.. I found a tutorial on the web which looks quite like the packet handling which flansmod has, and it was marked as _not recommended (anymore?)_.

I myself use in my mods a different packet system based on _"how they should be made in forge (at least currently)"_.
I might try someday soon to rewrite the packets/handling in flansmod. (or I'll just use the ones in FCL ...)

Also it all _could_ be related to some kind vanilla-anticheat, cause I never had in earlier versions of Minecraft "kick-back" issues when flying fastly on the server (it would timeout if I would overdo it normally).
_(not counting servers with anti-cheat plugins)_
The kick from the vehicle quite a lot reminds that kickback in creative,
it obviosly doesn't teleport the vehicle back aswel and causes the whole thing. #theory

**Comment by PrototypeTheta** [comment]
I do recall someone saying that the old Netty system was a pretty awful way to do it with the newer versions (IIRC Flan literally included a link to the tutorial he based the system off in one of the files).

I'm working on my own packet handler for my own vehicle mod. If it works I'll try and hook it into Flan's mod but there's really no guarantee. Even if it isn't causing the problem the whole thing could probably benefit from a rewrite.

It does sound like this anti cheat might be contributing but considering this occurs in other versions I don't believe it is the root of the problem.

**Comment by Fexcraft** [comment]
_deleted text here_
https://youtu.be/kE5bfn62XTM

**Comment by PrototypeTheta** [comment]
What exactly is different? That looks exactly like the "falling out of planes" bug the plagued 1.7.10 and 1.5.2 versions of the mod. Just seems to occur much much faster...

**Comment by Fexcraft** [comment]
I don't recall much of 1.7 and didn't play modded MP on 1.5.2, so idk about that...

**Comment by PrototypeTheta** [comment]
Basically that exact same bug would happen. But it would only happen in aircraft flying fast, and was possible to avoid if you flew high enough. Though you say this is different from before? I am curious what you mean by that.

It would also happen on 1.8, and I think the frequency of occurrence might have been different there but I never really verified that.

**Comment by Fexcraft** [comment]
I meant before that the bevavior changed a bit then it was a few weeks ago.
Might be just imagination though..

**Comment by my-thanks** [comment]
Please try to change code in EntitySeat.java like below and report to me how it works.
`
	@Override
	public void onUpdate()
	{
		super.onUpdate();
		//prevPosX = posX;
		//prevPosY = posY;
		//prevPosZ = posZ;

		if(driver && riddenByEntity==null)
		{
			prevLooking = looking.clone();
			prevPlayerLooking = playerLooking.clone();
		}
		

		//If on the client and the driveable parent has yet to be found, search for it
		if(worldObj.isRemote && !foundDriveable)
		{
			driveable = (EntityDriveable)worldObj.getEntityByID(driveableID);
			if(driveable == null)
				return;
			foundDriveable = true;
			driveable.seats[seatID] = this;
			seatInfo = driveable.getDriveableType().seats[seatID];
			looking.setAngles((seatInfo.minYaw + seatInfo.maxYaw) / 2, 0F, 0F);
			playerLooking.setAngles((seatInfo.minYaw + seatInfo.maxYaw) / 2, 0F, 0F);
			prevLooking = looking.clone();

			playerPosX = prevPlayerPosX = posX = driveable.posX;
			playerPosY = prevPlayerPosY = posY = driveable.posY;
			playerPosZ = prevPlayerPosZ = posZ = driveable.posZ;
			lastTickPosX = driveable.lastTickPosX; // synchronization with driveable
			lastTickPosY = driveable.lastTickPosY; // synchronization with driveable
			lastTickPosZ = driveable.lastTickPosZ; // synchronization with driveable
			
			setPosition(posX, posY, posZ);
`

**Comment by Fexcraft** [comment]
I'll test it.
(reminds me that I completly forgot to check the methods
in the entity classes after general update \*facepalm\*)

**Comment by my-thanks** [comment]
Ok. It's working for 1.7.10. At my mind there must be other "lastTick" variables in 1.10 Entity class. Should look for it. At my suggestion Forge don't make synchronize some variables in postprocess therefor we need to correct it.

**Comment by Fexcraft** [comment]
Atm trying out making a new packet handler and see if it's related to packets.

**Comment by PrototypeTheta** [comment]
Just tested on 1.7.10. I'm afraid it doesn't make much difference there either.

**Comment by my-thanks** [comment]
It works on SP. There need to rewrite packetHandler for MP

**Comment by PrototypeTheta** [comment]
Even in SP I can't get it to work.

Though in other news, I may have accidentally created a method to force the player to re-mount the vehicles after they have "fallen out". The catch being that you cannot exit the vehicle ever. I may be able to turn this into something useful but I am slightly doubtful, and would rather try and prevent it from happening in the first place.

**Comment by my-thanks** [comment]
> Even in SP I can't get it to work.

>Though in other news, I may have accidentally created a method to force the player to re-mount the >vehicles after they have "fallen out". The catch being that you cannot exit the vehicle ever. I may be able >to turn this into something useful but I am slightly doubtful, and would rather try and prevent it from >happening in the first place.

>EDIT: This is all on 1.7 mind you. 

Ok. I have a slow PC therefor I see change in "kick" effect. Yes, I mistaken, bug is still. But not for all vehicles (strange). I think this cause in player's position (lastTick position maybe) but I can't say that I'm right.

**Comment by PrototypeTheta** [comment]
If you really need to test it fly a fast plane on an amplified world.

**Comment by my-thanks** [comment]
I want to explain. Before change I had an effect of "abyss" for a some time before the "kick". At now chunks loading correctly("on-the-fly for my PC"). I tried to drive a plane that in " Manus Warhammer 40k Package". I have 100 throttle about two minutes! Then I was kicked from the plane :( I still think that is synchronization bug

**Comment by PrototypeTheta** [comment]
I believe this happens because somehow the game gets confused and resets the riddenByEntity of the seat to null. Just based on some debugging that I've done.

**Comment by Fexcraft** [comment]
Knowing minecraft I'd believe that.

_This also gives me a bit hacky but maybe effective idea to fix the kickout.. I'll test it later._

**Comment by Fexcraft** [comment]
Aftert testing it with an dedicated server, it did crash after a while due to timeout, "a single tick took 60.00 while max is 00.05" or something like that.

**Comment by PrototypeTheta** [comment]
The part I don't understand. Is that when the player is "kicked", the riddenByEntity appears to be set to null. However when you hit the exit key, that too, sets it to null (which it was already?), and yet teleports you to an entity which you should no longer have anything to do with?


Unless the seat stops recognising that it is ridden, and the players continues to recognise the seat? Which doesn't sound possible.

Also, out of curiosity, what "fix" are you trying to do here? Even if it doesn't work here if it would work on 1.7 that would be a huge help as I'm currently maintaining that version.

**Comment by Fexcraft** [comment]
> The part I don't understand. Is that when the player is "kicked", the riddenByEntity appears to be set to null. However when you hit the exit key, that too, sets it to null (which it was already?), and yet teleports you to an entity which you should no longer have anything to do with?

> Unless the seat stops recognising that it is ridden, and the players continues to recognise the seat? Which doesn't sound possible.

The vehicle also beheaves as if it still would have the passenger inside, and only after the player "dismounts" (and gets "teleported" to it), it stops like it should when it has no driver.


> Also, out of curiosity, what "fix" are you trying to do here? Even if it doesn't work here if it would work on 1.7 that would be a huge help as I'm currently maintaining that version.

I don't remember why I was doing this atm. 0.o

**Comment by my-thanks** [comment]
I was looked for code in other repositories for Entity. There no examle for directly "force"  equality of position Entity with Entity. I should try to rewrite code by the way to use vanilla builtin functions for Entities and Driveables.

**Comment by PrototypeTheta** [comment]
The chunk loading changed between 1.6.4 and 1.7.10 which is why the bug returned between those versions.

**Comment by my-thanks** [comment]
I found this in sourcecode of Minecraft at package net.minecraft.world.chunk.Chunk:

    _/**
     * Adds an entity to the chunk. Args: entity
     */
    public void addEntity(Entity entityIn)
    {
        this.hasEntities = true;
        int var2 = MathHelper.floor_double(entityIn.posX / 16.0D);
        int var3 = MathHelper.floor_double(entityIn.posZ / 16.0D);

        if (var2 != this.xPosition || var3 != this.zPosition)
        {
            logger.warn("Wrong location! (" + var2 + ", " + var3 + ") should be (" + this.xPosition + ", " + this.zPosition + "), " + entityIn, new Object[] {entityIn});
            entityIn.setDead();
         }
        int var4 = MathHelper.floor_double(entityIn.posY / 16.0D);

        if (var4 < 0)
        {
            var4 = 0;
        }

        if (var4 >= this.entityLists.length)
        {
            var4 = this.entityLists.length - 1;
        }

        entityIn.addedToChunk = true;
        entityIn.chunkCoordX = this.xPosition;
        entityIn.chunkCoordY = var4;
        entityIn.chunkCoordZ = this.zPosition;
        this.entityLists[var4].add(entityIn);
    }_


"entityIn.setDead(); " <--- I think this can be the reason for "kick" of the player. Maybe possible to override "addEntity"?

**Comment by Fexcraft** [comment]
>\*writing it down before I forget\*
TODO: check if the kickout happends on chunk boundaries

**Comment by Fexcraft** [comment]
I still don't know the cause why random key-presses are called on client side, "random" setDead() calls for the seats, etc.
But I might have found a way around with custom packets, I'll upload it when I'm sure it works as it should.

**Comment by Fexcraft** [comment]
The changes need testing if they at other computers too...
(had too many times that things working for me but for others not..)

**Comment by Enter03** [comment]
If you want, I can test Flans Mod Minus on my computer. Specifications:
Intel Core i7 Skylake 4Ghz, NVidia GTX 960 and 64 GB of ram, Polish version of Windows 10.

**Comment by Fexcraft** [comment]
Sure, it's not about specs I mean, more about the settings and all and difference in hardware which may affect something which I can't test with on pc.

Also there still exists a bug which would 'freeze' the game, but at least now (depending on situation) it's possible to simply leave the world and re-enter, this wasn't before possible since it freezed anything packet related. (vanilla too)
_since there is no log idk what is causing it, still experimenting on that_

**Comment by Enter03** [comment]
Is there any info about this bug?
---
Czy są już może jakieś informacje w sprawie tego błędu?

**Comment by Fexcraft** [comment]
I made is as stable as possible, currently in the 1.11 version the only issue is that after a (rather long compared to before) distance the chunks stop loading,
then either just wait some seconds till it re-syncs, or dismount and re-enter the vehicle.
Other than that it's rather stable. (should be similar in 1.10.2)
I do not know the source of the issues though.

**Comment by Enter03** [comment]
Ok. Thanks for trying to fix this. But can you please add these 1.11 patches to 1.10? I run server with my friend and we can't move all mods to 1.11! This mod is our must-have. We love tanks, guns and other Flans mod Stuff.

**Comment by Fexcraft** [comment]
Cannot guarantee, it's a headache and I'm not always in the mood to do such .-.

**Comment by Fexcraft** [comment]
This issue seems to be fixed in the new `minus-1.11.2` branch.

**Comment by Enter03** [comment]
I will compile it and give you info!
(I will test by using fastest planes)

**Comment by Fexcraft** [comment]
Ah shit.. no, I didn't fix/check the planes code yet, they don't work for _surr_.
You should try some fast vehicle maybe. (I tested so far with Humvee, T1/_1, OT1)
